;this file is automatically generated by generate_interrupt_stubs.py

extern set_interrupt_handler
extern handle_interrupt
data_segment_selector equ 2<<3
global setup_all_interrupts
global trap_return
section .text
setup_all_interrupts:
call setup_interrupt_0
call setup_interrupt_1
call setup_interrupt_2
call setup_interrupt_3
call setup_interrupt_4
call setup_interrupt_5
call setup_interrupt_6
call setup_interrupt_7
call setup_interrupt_8
call setup_interrupt_9
call setup_interrupt_10
call setup_interrupt_11
call setup_interrupt_12
call setup_interrupt_13
call setup_interrupt_14
call setup_interrupt_15
call setup_interrupt_16
call setup_interrupt_17
call setup_interrupt_18
call setup_interrupt_19
call setup_interrupt_20
call setup_interrupt_21
call setup_interrupt_22
call setup_interrupt_23
call setup_interrupt_24
call setup_interrupt_25
call setup_interrupt_26
call setup_interrupt_27
call setup_interrupt_28
call setup_interrupt_29
call setup_interrupt_30
call setup_interrupt_31
call setup_interrupt_32
call setup_interrupt_33
call setup_interrupt_34
call setup_interrupt_35
call setup_interrupt_36
call setup_interrupt_37
call setup_interrupt_38
call setup_interrupt_39
call setup_interrupt_40
call setup_interrupt_41
call setup_interrupt_42
call setup_interrupt_43
call setup_interrupt_44
call setup_interrupt_45
call setup_interrupt_46
call setup_interrupt_47
call setup_interrupt_48
call setup_interrupt_49
call setup_interrupt_50
call setup_interrupt_51
call setup_interrupt_52
call setup_interrupt_53
call setup_interrupt_54
call setup_interrupt_55
call setup_interrupt_56
call setup_interrupt_57
call setup_interrupt_58
call setup_interrupt_59
call setup_interrupt_60
call setup_interrupt_61
call setup_interrupt_62
call setup_interrupt_63
call setup_interrupt_64
call setup_interrupt_65
call setup_interrupt_66
call setup_interrupt_67
call setup_interrupt_68
call setup_interrupt_69
call setup_interrupt_70
call setup_interrupt_71
call setup_interrupt_72
call setup_interrupt_73
call setup_interrupt_74
call setup_interrupt_75
call setup_interrupt_76
call setup_interrupt_77
call setup_interrupt_78
call setup_interrupt_79
call setup_interrupt_80
call setup_interrupt_81
call setup_interrupt_82
call setup_interrupt_83
call setup_interrupt_84
call setup_interrupt_85
call setup_interrupt_86
call setup_interrupt_87
call setup_interrupt_88
call setup_interrupt_89
call setup_interrupt_90
call setup_interrupt_91
call setup_interrupt_92
call setup_interrupt_93
call setup_interrupt_94
call setup_interrupt_95
call setup_interrupt_96
call setup_interrupt_97
call setup_interrupt_98
call setup_interrupt_99
call setup_interrupt_100
call setup_interrupt_101
call setup_interrupt_102
call setup_interrupt_103
call setup_interrupt_104
call setup_interrupt_105
call setup_interrupt_106
call setup_interrupt_107
call setup_interrupt_108
call setup_interrupt_109
call setup_interrupt_110
call setup_interrupt_111
call setup_interrupt_112
call setup_interrupt_113
call setup_interrupt_114
call setup_interrupt_115
call setup_interrupt_116
call setup_interrupt_117
call setup_interrupt_118
call setup_interrupt_119
call setup_interrupt_120
call setup_interrupt_121
call setup_interrupt_122
call setup_interrupt_123
call setup_interrupt_124
call setup_interrupt_125
call setup_interrupt_126
call setup_interrupt_127
call setup_interrupt_128
call setup_interrupt_129
call setup_interrupt_130
call setup_interrupt_131
call setup_interrupt_132
call setup_interrupt_133
call setup_interrupt_134
call setup_interrupt_135
call setup_interrupt_136
call setup_interrupt_137
call setup_interrupt_138
call setup_interrupt_139
call setup_interrupt_140
call setup_interrupt_141
call setup_interrupt_142
call setup_interrupt_143
call setup_interrupt_144
call setup_interrupt_145
call setup_interrupt_146
call setup_interrupt_147
call setup_interrupt_148
call setup_interrupt_149
call setup_interrupt_150
call setup_interrupt_151
call setup_interrupt_152
call setup_interrupt_153
call setup_interrupt_154
call setup_interrupt_155
call setup_interrupt_156
call setup_interrupt_157
call setup_interrupt_158
call setup_interrupt_159
call setup_interrupt_160
call setup_interrupt_161
call setup_interrupt_162
call setup_interrupt_163
call setup_interrupt_164
call setup_interrupt_165
call setup_interrupt_166
call setup_interrupt_167
call setup_interrupt_168
call setup_interrupt_169
call setup_interrupt_170
call setup_interrupt_171
call setup_interrupt_172
call setup_interrupt_173
call setup_interrupt_174
call setup_interrupt_175
call setup_interrupt_176
call setup_interrupt_177
call setup_interrupt_178
call setup_interrupt_179
call setup_interrupt_180
call setup_interrupt_181
call setup_interrupt_182
call setup_interrupt_183
call setup_interrupt_184
call setup_interrupt_185
call setup_interrupt_186
call setup_interrupt_187
call setup_interrupt_188
call setup_interrupt_189
call setup_interrupt_190
call setup_interrupt_191
call setup_interrupt_192
call setup_interrupt_193
call setup_interrupt_194
call setup_interrupt_195
call setup_interrupt_196
call setup_interrupt_197
call setup_interrupt_198
call setup_interrupt_199
call setup_interrupt_200
call setup_interrupt_201
call setup_interrupt_202
call setup_interrupt_203
call setup_interrupt_204
call setup_interrupt_205
call setup_interrupt_206
call setup_interrupt_207
call setup_interrupt_208
call setup_interrupt_209
call setup_interrupt_210
call setup_interrupt_211
call setup_interrupt_212
call setup_interrupt_213
call setup_interrupt_214
call setup_interrupt_215
call setup_interrupt_216
call setup_interrupt_217
call setup_interrupt_218
call setup_interrupt_219
call setup_interrupt_220
call setup_interrupt_221
call setup_interrupt_222
call setup_interrupt_223
call setup_interrupt_224
call setup_interrupt_225
call setup_interrupt_226
call setup_interrupt_227
call setup_interrupt_228
call setup_interrupt_229
call setup_interrupt_230
call setup_interrupt_231
call setup_interrupt_232
call setup_interrupt_233
call setup_interrupt_234
call setup_interrupt_235
call setup_interrupt_236
call setup_interrupt_237
call setup_interrupt_238
call setup_interrupt_239
call setup_interrupt_240
call setup_interrupt_241
call setup_interrupt_242
call setup_interrupt_243
call setup_interrupt_244
call setup_interrupt_245
call setup_interrupt_246
call setup_interrupt_247
call setup_interrupt_248
call setup_interrupt_249
call setup_interrupt_250
call setup_interrupt_251
call setup_interrupt_252
call setup_interrupt_253
call setup_interrupt_254
call setup_interrupt_255
ret

setup_interrupt_0:
push interrupt_stub_0
push 0
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_1:
push interrupt_stub_1
push 1
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_2:
push interrupt_stub_2
push 2
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_3:
push interrupt_stub_3
push 3
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_4:
push interrupt_stub_4
push 4
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_5:
push interrupt_stub_5
push 5
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_6:
push interrupt_stub_6
push 6
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_7:
push interrupt_stub_7
push 7
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_8:
push interrupt_stub_8
push 8
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_9:
push interrupt_stub_9
push 9
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_10:
push interrupt_stub_10
push 10
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_11:
push interrupt_stub_11
push 11
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_12:
push interrupt_stub_12
push 12
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_13:
push interrupt_stub_13
push 13
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_14:
push interrupt_stub_14
push 14
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_15:
push interrupt_stub_15
push 15
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_16:
push interrupt_stub_16
push 16
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_17:
push interrupt_stub_17
push 17
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_18:
push interrupt_stub_18
push 18
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_19:
push interrupt_stub_19
push 19
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_20:
push interrupt_stub_20
push 20
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_21:
push interrupt_stub_21
push 21
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_22:
push interrupt_stub_22
push 22
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_23:
push interrupt_stub_23
push 23
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_24:
push interrupt_stub_24
push 24
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_25:
push interrupt_stub_25
push 25
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_26:
push interrupt_stub_26
push 26
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_27:
push interrupt_stub_27
push 27
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_28:
push interrupt_stub_28
push 28
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_29:
push interrupt_stub_29
push 29
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_30:
push interrupt_stub_30
push 30
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_31:
push interrupt_stub_31
push 31
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_32:
push interrupt_stub_32
push 32
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_33:
push interrupt_stub_33
push 33
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_34:
push interrupt_stub_34
push 34
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_35:
push interrupt_stub_35
push 35
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_36:
push interrupt_stub_36
push 36
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_37:
push interrupt_stub_37
push 37
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_38:
push interrupt_stub_38
push 38
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_39:
push interrupt_stub_39
push 39
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_40:
push interrupt_stub_40
push 40
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_41:
push interrupt_stub_41
push 41
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_42:
push interrupt_stub_42
push 42
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_43:
push interrupt_stub_43
push 43
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_44:
push interrupt_stub_44
push 44
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_45:
push interrupt_stub_45
push 45
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_46:
push interrupt_stub_46
push 46
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_47:
push interrupt_stub_47
push 47
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_48:
push interrupt_stub_48
push 48
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_49:
push interrupt_stub_49
push 49
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_50:
push interrupt_stub_50
push 50
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_51:
push interrupt_stub_51
push 51
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_52:
push interrupt_stub_52
push 52
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_53:
push interrupt_stub_53
push 53
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_54:
push interrupt_stub_54
push 54
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_55:
push interrupt_stub_55
push 55
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_56:
push interrupt_stub_56
push 56
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_57:
push interrupt_stub_57
push 57
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_58:
push interrupt_stub_58
push 58
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_59:
push interrupt_stub_59
push 59
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_60:
push interrupt_stub_60
push 60
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_61:
push interrupt_stub_61
push 61
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_62:
push interrupt_stub_62
push 62
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_63:
push interrupt_stub_63
push 63
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_64:
push interrupt_stub_64
push 64
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_65:
push interrupt_stub_65
push 65
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_66:
push interrupt_stub_66
push 66
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_67:
push interrupt_stub_67
push 67
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_68:
push interrupt_stub_68
push 68
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_69:
push interrupt_stub_69
push 69
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_70:
push interrupt_stub_70
push 70
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_71:
push interrupt_stub_71
push 71
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_72:
push interrupt_stub_72
push 72
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_73:
push interrupt_stub_73
push 73
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_74:
push interrupt_stub_74
push 74
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_75:
push interrupt_stub_75
push 75
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_76:
push interrupt_stub_76
push 76
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_77:
push interrupt_stub_77
push 77
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_78:
push interrupt_stub_78
push 78
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_79:
push interrupt_stub_79
push 79
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_80:
push interrupt_stub_80
push 80
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_81:
push interrupt_stub_81
push 81
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_82:
push interrupt_stub_82
push 82
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_83:
push interrupt_stub_83
push 83
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_84:
push interrupt_stub_84
push 84
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_85:
push interrupt_stub_85
push 85
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_86:
push interrupt_stub_86
push 86
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_87:
push interrupt_stub_87
push 87
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_88:
push interrupt_stub_88
push 88
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_89:
push interrupt_stub_89
push 89
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_90:
push interrupt_stub_90
push 90
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_91:
push interrupt_stub_91
push 91
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_92:
push interrupt_stub_92
push 92
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_93:
push interrupt_stub_93
push 93
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_94:
push interrupt_stub_94
push 94
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_95:
push interrupt_stub_95
push 95
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_96:
push interrupt_stub_96
push 96
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_97:
push interrupt_stub_97
push 97
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_98:
push interrupt_stub_98
push 98
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_99:
push interrupt_stub_99
push 99
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_100:
push interrupt_stub_100
push 100
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_101:
push interrupt_stub_101
push 101
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_102:
push interrupt_stub_102
push 102
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_103:
push interrupt_stub_103
push 103
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_104:
push interrupt_stub_104
push 104
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_105:
push interrupt_stub_105
push 105
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_106:
push interrupt_stub_106
push 106
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_107:
push interrupt_stub_107
push 107
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_108:
push interrupt_stub_108
push 108
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_109:
push interrupt_stub_109
push 109
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_110:
push interrupt_stub_110
push 110
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_111:
push interrupt_stub_111
push 111
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_112:
push interrupt_stub_112
push 112
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_113:
push interrupt_stub_113
push 113
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_114:
push interrupt_stub_114
push 114
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_115:
push interrupt_stub_115
push 115
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_116:
push interrupt_stub_116
push 116
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_117:
push interrupt_stub_117
push 117
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_118:
push interrupt_stub_118
push 118
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_119:
push interrupt_stub_119
push 119
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_120:
push interrupt_stub_120
push 120
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_121:
push interrupt_stub_121
push 121
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_122:
push interrupt_stub_122
push 122
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_123:
push interrupt_stub_123
push 123
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_124:
push interrupt_stub_124
push 124
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_125:
push interrupt_stub_125
push 125
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_126:
push interrupt_stub_126
push 126
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_127:
push interrupt_stub_127
push 127
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_128:
push interrupt_stub_128
push 128
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_129:
push interrupt_stub_129
push 129
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_130:
push interrupt_stub_130
push 130
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_131:
push interrupt_stub_131
push 131
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_132:
push interrupt_stub_132
push 132
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_133:
push interrupt_stub_133
push 133
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_134:
push interrupt_stub_134
push 134
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_135:
push interrupt_stub_135
push 135
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_136:
push interrupt_stub_136
push 136
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_137:
push interrupt_stub_137
push 137
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_138:
push interrupt_stub_138
push 138
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_139:
push interrupt_stub_139
push 139
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_140:
push interrupt_stub_140
push 140
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_141:
push interrupt_stub_141
push 141
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_142:
push interrupt_stub_142
push 142
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_143:
push interrupt_stub_143
push 143
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_144:
push interrupt_stub_144
push 144
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_145:
push interrupt_stub_145
push 145
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_146:
push interrupt_stub_146
push 146
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_147:
push interrupt_stub_147
push 147
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_148:
push interrupt_stub_148
push 148
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_149:
push interrupt_stub_149
push 149
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_150:
push interrupt_stub_150
push 150
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_151:
push interrupt_stub_151
push 151
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_152:
push interrupt_stub_152
push 152
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_153:
push interrupt_stub_153
push 153
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_154:
push interrupt_stub_154
push 154
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_155:
push interrupt_stub_155
push 155
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_156:
push interrupt_stub_156
push 156
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_157:
push interrupt_stub_157
push 157
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_158:
push interrupt_stub_158
push 158
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_159:
push interrupt_stub_159
push 159
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_160:
push interrupt_stub_160
push 160
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_161:
push interrupt_stub_161
push 161
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_162:
push interrupt_stub_162
push 162
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_163:
push interrupt_stub_163
push 163
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_164:
push interrupt_stub_164
push 164
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_165:
push interrupt_stub_165
push 165
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_166:
push interrupt_stub_166
push 166
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_167:
push interrupt_stub_167
push 167
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_168:
push interrupt_stub_168
push 168
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_169:
push interrupt_stub_169
push 169
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_170:
push interrupt_stub_170
push 170
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_171:
push interrupt_stub_171
push 171
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_172:
push interrupt_stub_172
push 172
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_173:
push interrupt_stub_173
push 173
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_174:
push interrupt_stub_174
push 174
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_175:
push interrupt_stub_175
push 175
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_176:
push interrupt_stub_176
push 176
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_177:
push interrupt_stub_177
push 177
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_178:
push interrupt_stub_178
push 178
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_179:
push interrupt_stub_179
push 179
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_180:
push interrupt_stub_180
push 180
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_181:
push interrupt_stub_181
push 181
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_182:
push interrupt_stub_182
push 182
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_183:
push interrupt_stub_183
push 183
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_184:
push interrupt_stub_184
push 184
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_185:
push interrupt_stub_185
push 185
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_186:
push interrupt_stub_186
push 186
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_187:
push interrupt_stub_187
push 187
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_188:
push interrupt_stub_188
push 188
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_189:
push interrupt_stub_189
push 189
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_190:
push interrupt_stub_190
push 190
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_191:
push interrupt_stub_191
push 191
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_192:
push interrupt_stub_192
push 192
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_193:
push interrupt_stub_193
push 193
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_194:
push interrupt_stub_194
push 194
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_195:
push interrupt_stub_195
push 195
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_196:
push interrupt_stub_196
push 196
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_197:
push interrupt_stub_197
push 197
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_198:
push interrupt_stub_198
push 198
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_199:
push interrupt_stub_199
push 199
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_200:
push interrupt_stub_200
push 200
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_201:
push interrupt_stub_201
push 201
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_202:
push interrupt_stub_202
push 202
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_203:
push interrupt_stub_203
push 203
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_204:
push interrupt_stub_204
push 204
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_205:
push interrupt_stub_205
push 205
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_206:
push interrupt_stub_206
push 206
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_207:
push interrupt_stub_207
push 207
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_208:
push interrupt_stub_208
push 208
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_209:
push interrupt_stub_209
push 209
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_210:
push interrupt_stub_210
push 210
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_211:
push interrupt_stub_211
push 211
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_212:
push interrupt_stub_212
push 212
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_213:
push interrupt_stub_213
push 213
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_214:
push interrupt_stub_214
push 214
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_215:
push interrupt_stub_215
push 215
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_216:
push interrupt_stub_216
push 216
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_217:
push interrupt_stub_217
push 217
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_218:
push interrupt_stub_218
push 218
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_219:
push interrupt_stub_219
push 219
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_220:
push interrupt_stub_220
push 220
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_221:
push interrupt_stub_221
push 221
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_222:
push interrupt_stub_222
push 222
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_223:
push interrupt_stub_223
push 223
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_224:
push interrupt_stub_224
push 224
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_225:
push interrupt_stub_225
push 225
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_226:
push interrupt_stub_226
push 226
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_227:
push interrupt_stub_227
push 227
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_228:
push interrupt_stub_228
push 228
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_229:
push interrupt_stub_229
push 229
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_230:
push interrupt_stub_230
push 230
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_231:
push interrupt_stub_231
push 231
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_232:
push interrupt_stub_232
push 232
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_233:
push interrupt_stub_233
push 233
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_234:
push interrupt_stub_234
push 234
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_235:
push interrupt_stub_235
push 235
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_236:
push interrupt_stub_236
push 236
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_237:
push interrupt_stub_237
push 237
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_238:
push interrupt_stub_238
push 238
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_239:
push interrupt_stub_239
push 239
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_240:
push interrupt_stub_240
push 240
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_241:
push interrupt_stub_241
push 241
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_242:
push interrupt_stub_242
push 242
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_243:
push interrupt_stub_243
push 243
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_244:
push interrupt_stub_244
push 244
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_245:
push interrupt_stub_245
push 245
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_246:
push interrupt_stub_246
push 246
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_247:
push interrupt_stub_247
push 247
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_248:
push interrupt_stub_248
push 248
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_249:
push interrupt_stub_249
push 249
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_250:
push interrupt_stub_250
push 250
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_251:
push interrupt_stub_251
push 251
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_252:
push interrupt_stub_252
push 252
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_253:
push interrupt_stub_253
push 253
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_254:
push interrupt_stub_254
push 254
call set_interrupt_handler
add esp, 8
ret

setup_interrupt_255:
push interrupt_stub_255
push 255
call set_interrupt_handler
add esp, 8
ret

interrupt_stub_0:
; not an exception, we set the error code manually to 0
push 0
push 0
jmp interrupt_stubs_common

interrupt_stub_1:
; not an exception, we set the error code manually to 0
push 0
push 1
jmp interrupt_stubs_common

interrupt_stub_2:
; not an exception, we set the error code manually to 0
push 0
push 2
jmp interrupt_stubs_common

interrupt_stub_3:
; not an exception, we set the error code manually to 0
push 0
push 3
jmp interrupt_stubs_common

interrupt_stub_4:
; not an exception, we set the error code manually to 0
push 0
push 4
jmp interrupt_stubs_common

interrupt_stub_5:
; not an exception, we set the error code manually to 0
push 0
push 5
jmp interrupt_stubs_common

interrupt_stub_6:
; not an exception, we set the error code manually to 0
push 0
push 6
jmp interrupt_stubs_common

interrupt_stub_7:
; not an exception, we set the error code manually to 0
push 0
push 7
jmp interrupt_stubs_common

interrupt_stub_8:
push 8
jmp interrupt_stubs_common

interrupt_stub_9:
; not an exception, we set the error code manually to 0
push 0
push 9
jmp interrupt_stubs_common

interrupt_stub_10:
push 10
jmp interrupt_stubs_common

interrupt_stub_11:
push 11
jmp interrupt_stubs_common

interrupt_stub_12:
push 12
jmp interrupt_stubs_common

interrupt_stub_13:
push 13
jmp interrupt_stubs_common

interrupt_stub_14:
push 14
jmp interrupt_stubs_common

interrupt_stub_15:
; not an exception, we set the error code manually to 0
push 0
push 15
jmp interrupt_stubs_common

interrupt_stub_16:
; not an exception, we set the error code manually to 0
push 0
push 16
jmp interrupt_stubs_common

interrupt_stub_17:
push 17
jmp interrupt_stubs_common

interrupt_stub_18:
; not an exception, we set the error code manually to 0
push 0
push 18
jmp interrupt_stubs_common

interrupt_stub_19:
; not an exception, we set the error code manually to 0
push 0
push 19
jmp interrupt_stubs_common

interrupt_stub_20:
; not an exception, we set the error code manually to 0
push 0
push 20
jmp interrupt_stubs_common

interrupt_stub_21:
; not an exception, we set the error code manually to 0
push 0
push 21
jmp interrupt_stubs_common

interrupt_stub_22:
; not an exception, we set the error code manually to 0
push 0
push 22
jmp interrupt_stubs_common

interrupt_stub_23:
; not an exception, we set the error code manually to 0
push 0
push 23
jmp interrupt_stubs_common

interrupt_stub_24:
; not an exception, we set the error code manually to 0
push 0
push 24
jmp interrupt_stubs_common

interrupt_stub_25:
; not an exception, we set the error code manually to 0
push 0
push 25
jmp interrupt_stubs_common

interrupt_stub_26:
; not an exception, we set the error code manually to 0
push 0
push 26
jmp interrupt_stubs_common

interrupt_stub_27:
; not an exception, we set the error code manually to 0
push 0
push 27
jmp interrupt_stubs_common

interrupt_stub_28:
; not an exception, we set the error code manually to 0
push 0
push 28
jmp interrupt_stubs_common

interrupt_stub_29:
; not an exception, we set the error code manually to 0
push 0
push 29
jmp interrupt_stubs_common

interrupt_stub_30:
; not an exception, we set the error code manually to 0
push 0
push 30
jmp interrupt_stubs_common

interrupt_stub_31:
; not an exception, we set the error code manually to 0
push 0
push 31
jmp interrupt_stubs_common

interrupt_stub_32:
; not an exception, we set the error code manually to 0
push 0
push 32
jmp interrupt_stubs_common

interrupt_stub_33:
; not an exception, we set the error code manually to 0
push 0
push 33
jmp interrupt_stubs_common

interrupt_stub_34:
; not an exception, we set the error code manually to 0
push 0
push 34
jmp interrupt_stubs_common

interrupt_stub_35:
; not an exception, we set the error code manually to 0
push 0
push 35
jmp interrupt_stubs_common

interrupt_stub_36:
; not an exception, we set the error code manually to 0
push 0
push 36
jmp interrupt_stubs_common

interrupt_stub_37:
; not an exception, we set the error code manually to 0
push 0
push 37
jmp interrupt_stubs_common

interrupt_stub_38:
; not an exception, we set the error code manually to 0
push 0
push 38
jmp interrupt_stubs_common

interrupt_stub_39:
; not an exception, we set the error code manually to 0
push 0
push 39
jmp interrupt_stubs_common

interrupt_stub_40:
; not an exception, we set the error code manually to 0
push 0
push 40
jmp interrupt_stubs_common

interrupt_stub_41:
; not an exception, we set the error code manually to 0
push 0
push 41
jmp interrupt_stubs_common

interrupt_stub_42:
; not an exception, we set the error code manually to 0
push 0
push 42
jmp interrupt_stubs_common

interrupt_stub_43:
; not an exception, we set the error code manually to 0
push 0
push 43
jmp interrupt_stubs_common

interrupt_stub_44:
; not an exception, we set the error code manually to 0
push 0
push 44
jmp interrupt_stubs_common

interrupt_stub_45:
; not an exception, we set the error code manually to 0
push 0
push 45
jmp interrupt_stubs_common

interrupt_stub_46:
; not an exception, we set the error code manually to 0
push 0
push 46
jmp interrupt_stubs_common

interrupt_stub_47:
; not an exception, we set the error code manually to 0
push 0
push 47
jmp interrupt_stubs_common

interrupt_stub_48:
; not an exception, we set the error code manually to 0
push 0
push 48
jmp interrupt_stubs_common

interrupt_stub_49:
; not an exception, we set the error code manually to 0
push 0
push 49
jmp interrupt_stubs_common

interrupt_stub_50:
; not an exception, we set the error code manually to 0
push 0
push 50
jmp interrupt_stubs_common

interrupt_stub_51:
; not an exception, we set the error code manually to 0
push 0
push 51
jmp interrupt_stubs_common

interrupt_stub_52:
; not an exception, we set the error code manually to 0
push 0
push 52
jmp interrupt_stubs_common

interrupt_stub_53:
; not an exception, we set the error code manually to 0
push 0
push 53
jmp interrupt_stubs_common

interrupt_stub_54:
; not an exception, we set the error code manually to 0
push 0
push 54
jmp interrupt_stubs_common

interrupt_stub_55:
; not an exception, we set the error code manually to 0
push 0
push 55
jmp interrupt_stubs_common

interrupt_stub_56:
; not an exception, we set the error code manually to 0
push 0
push 56
jmp interrupt_stubs_common

interrupt_stub_57:
; not an exception, we set the error code manually to 0
push 0
push 57
jmp interrupt_stubs_common

interrupt_stub_58:
; not an exception, we set the error code manually to 0
push 0
push 58
jmp interrupt_stubs_common

interrupt_stub_59:
; not an exception, we set the error code manually to 0
push 0
push 59
jmp interrupt_stubs_common

interrupt_stub_60:
; not an exception, we set the error code manually to 0
push 0
push 60
jmp interrupt_stubs_common

interrupt_stub_61:
; not an exception, we set the error code manually to 0
push 0
push 61
jmp interrupt_stubs_common

interrupt_stub_62:
; not an exception, we set the error code manually to 0
push 0
push 62
jmp interrupt_stubs_common

interrupt_stub_63:
; not an exception, we set the error code manually to 0
push 0
push 63
jmp interrupt_stubs_common

interrupt_stub_64:
; not an exception, we set the error code manually to 0
push 0
push 64
jmp interrupt_stubs_common

interrupt_stub_65:
; not an exception, we set the error code manually to 0
push 0
push 65
jmp interrupt_stubs_common

interrupt_stub_66:
; not an exception, we set the error code manually to 0
push 0
push 66
jmp interrupt_stubs_common

interrupt_stub_67:
; not an exception, we set the error code manually to 0
push 0
push 67
jmp interrupt_stubs_common

interrupt_stub_68:
; not an exception, we set the error code manually to 0
push 0
push 68
jmp interrupt_stubs_common

interrupt_stub_69:
; not an exception, we set the error code manually to 0
push 0
push 69
jmp interrupt_stubs_common

interrupt_stub_70:
; not an exception, we set the error code manually to 0
push 0
push 70
jmp interrupt_stubs_common

interrupt_stub_71:
; not an exception, we set the error code manually to 0
push 0
push 71
jmp interrupt_stubs_common

interrupt_stub_72:
; not an exception, we set the error code manually to 0
push 0
push 72
jmp interrupt_stubs_common

interrupt_stub_73:
; not an exception, we set the error code manually to 0
push 0
push 73
jmp interrupt_stubs_common

interrupt_stub_74:
; not an exception, we set the error code manually to 0
push 0
push 74
jmp interrupt_stubs_common

interrupt_stub_75:
; not an exception, we set the error code manually to 0
push 0
push 75
jmp interrupt_stubs_common

interrupt_stub_76:
; not an exception, we set the error code manually to 0
push 0
push 76
jmp interrupt_stubs_common

interrupt_stub_77:
; not an exception, we set the error code manually to 0
push 0
push 77
jmp interrupt_stubs_common

interrupt_stub_78:
; not an exception, we set the error code manually to 0
push 0
push 78
jmp interrupt_stubs_common

interrupt_stub_79:
; not an exception, we set the error code manually to 0
push 0
push 79
jmp interrupt_stubs_common

interrupt_stub_80:
; not an exception, we set the error code manually to 0
push 0
push 80
jmp interrupt_stubs_common

interrupt_stub_81:
; not an exception, we set the error code manually to 0
push 0
push 81
jmp interrupt_stubs_common

interrupt_stub_82:
; not an exception, we set the error code manually to 0
push 0
push 82
jmp interrupt_stubs_common

interrupt_stub_83:
; not an exception, we set the error code manually to 0
push 0
push 83
jmp interrupt_stubs_common

interrupt_stub_84:
; not an exception, we set the error code manually to 0
push 0
push 84
jmp interrupt_stubs_common

interrupt_stub_85:
; not an exception, we set the error code manually to 0
push 0
push 85
jmp interrupt_stubs_common

interrupt_stub_86:
; not an exception, we set the error code manually to 0
push 0
push 86
jmp interrupt_stubs_common

interrupt_stub_87:
; not an exception, we set the error code manually to 0
push 0
push 87
jmp interrupt_stubs_common

interrupt_stub_88:
; not an exception, we set the error code manually to 0
push 0
push 88
jmp interrupt_stubs_common

interrupt_stub_89:
; not an exception, we set the error code manually to 0
push 0
push 89
jmp interrupt_stubs_common

interrupt_stub_90:
; not an exception, we set the error code manually to 0
push 0
push 90
jmp interrupt_stubs_common

interrupt_stub_91:
; not an exception, we set the error code manually to 0
push 0
push 91
jmp interrupt_stubs_common

interrupt_stub_92:
; not an exception, we set the error code manually to 0
push 0
push 92
jmp interrupt_stubs_common

interrupt_stub_93:
; not an exception, we set the error code manually to 0
push 0
push 93
jmp interrupt_stubs_common

interrupt_stub_94:
; not an exception, we set the error code manually to 0
push 0
push 94
jmp interrupt_stubs_common

interrupt_stub_95:
; not an exception, we set the error code manually to 0
push 0
push 95
jmp interrupt_stubs_common

interrupt_stub_96:
; not an exception, we set the error code manually to 0
push 0
push 96
jmp interrupt_stubs_common

interrupt_stub_97:
; not an exception, we set the error code manually to 0
push 0
push 97
jmp interrupt_stubs_common

interrupt_stub_98:
; not an exception, we set the error code manually to 0
push 0
push 98
jmp interrupt_stubs_common

interrupt_stub_99:
; not an exception, we set the error code manually to 0
push 0
push 99
jmp interrupt_stubs_common

interrupt_stub_100:
; not an exception, we set the error code manually to 0
push 0
push 100
jmp interrupt_stubs_common

interrupt_stub_101:
; not an exception, we set the error code manually to 0
push 0
push 101
jmp interrupt_stubs_common

interrupt_stub_102:
; not an exception, we set the error code manually to 0
push 0
push 102
jmp interrupt_stubs_common

interrupt_stub_103:
; not an exception, we set the error code manually to 0
push 0
push 103
jmp interrupt_stubs_common

interrupt_stub_104:
; not an exception, we set the error code manually to 0
push 0
push 104
jmp interrupt_stubs_common

interrupt_stub_105:
; not an exception, we set the error code manually to 0
push 0
push 105
jmp interrupt_stubs_common

interrupt_stub_106:
; not an exception, we set the error code manually to 0
push 0
push 106
jmp interrupt_stubs_common

interrupt_stub_107:
; not an exception, we set the error code manually to 0
push 0
push 107
jmp interrupt_stubs_common

interrupt_stub_108:
; not an exception, we set the error code manually to 0
push 0
push 108
jmp interrupt_stubs_common

interrupt_stub_109:
; not an exception, we set the error code manually to 0
push 0
push 109
jmp interrupt_stubs_common

interrupt_stub_110:
; not an exception, we set the error code manually to 0
push 0
push 110
jmp interrupt_stubs_common

interrupt_stub_111:
; not an exception, we set the error code manually to 0
push 0
push 111
jmp interrupt_stubs_common

interrupt_stub_112:
; not an exception, we set the error code manually to 0
push 0
push 112
jmp interrupt_stubs_common

interrupt_stub_113:
; not an exception, we set the error code manually to 0
push 0
push 113
jmp interrupt_stubs_common

interrupt_stub_114:
; not an exception, we set the error code manually to 0
push 0
push 114
jmp interrupt_stubs_common

interrupt_stub_115:
; not an exception, we set the error code manually to 0
push 0
push 115
jmp interrupt_stubs_common

interrupt_stub_116:
; not an exception, we set the error code manually to 0
push 0
push 116
jmp interrupt_stubs_common

interrupt_stub_117:
; not an exception, we set the error code manually to 0
push 0
push 117
jmp interrupt_stubs_common

interrupt_stub_118:
; not an exception, we set the error code manually to 0
push 0
push 118
jmp interrupt_stubs_common

interrupt_stub_119:
; not an exception, we set the error code manually to 0
push 0
push 119
jmp interrupt_stubs_common

interrupt_stub_120:
; not an exception, we set the error code manually to 0
push 0
push 120
jmp interrupt_stubs_common

interrupt_stub_121:
; not an exception, we set the error code manually to 0
push 0
push 121
jmp interrupt_stubs_common

interrupt_stub_122:
; not an exception, we set the error code manually to 0
push 0
push 122
jmp interrupt_stubs_common

interrupt_stub_123:
; not an exception, we set the error code manually to 0
push 0
push 123
jmp interrupt_stubs_common

interrupt_stub_124:
; not an exception, we set the error code manually to 0
push 0
push 124
jmp interrupt_stubs_common

interrupt_stub_125:
; not an exception, we set the error code manually to 0
push 0
push 125
jmp interrupt_stubs_common

interrupt_stub_126:
; not an exception, we set the error code manually to 0
push 0
push 126
jmp interrupt_stubs_common

interrupt_stub_127:
; not an exception, we set the error code manually to 0
push 0
push 127
jmp interrupt_stubs_common

interrupt_stub_128:
; not an exception, we set the error code manually to 0
push 0
push 128
jmp interrupt_stubs_common

interrupt_stub_129:
; not an exception, we set the error code manually to 0
push 0
push 129
jmp interrupt_stubs_common

interrupt_stub_130:
; not an exception, we set the error code manually to 0
push 0
push 130
jmp interrupt_stubs_common

interrupt_stub_131:
; not an exception, we set the error code manually to 0
push 0
push 131
jmp interrupt_stubs_common

interrupt_stub_132:
; not an exception, we set the error code manually to 0
push 0
push 132
jmp interrupt_stubs_common

interrupt_stub_133:
; not an exception, we set the error code manually to 0
push 0
push 133
jmp interrupt_stubs_common

interrupt_stub_134:
; not an exception, we set the error code manually to 0
push 0
push 134
jmp interrupt_stubs_common

interrupt_stub_135:
; not an exception, we set the error code manually to 0
push 0
push 135
jmp interrupt_stubs_common

interrupt_stub_136:
; not an exception, we set the error code manually to 0
push 0
push 136
jmp interrupt_stubs_common

interrupt_stub_137:
; not an exception, we set the error code manually to 0
push 0
push 137
jmp interrupt_stubs_common

interrupt_stub_138:
; not an exception, we set the error code manually to 0
push 0
push 138
jmp interrupt_stubs_common

interrupt_stub_139:
; not an exception, we set the error code manually to 0
push 0
push 139
jmp interrupt_stubs_common

interrupt_stub_140:
; not an exception, we set the error code manually to 0
push 0
push 140
jmp interrupt_stubs_common

interrupt_stub_141:
; not an exception, we set the error code manually to 0
push 0
push 141
jmp interrupt_stubs_common

interrupt_stub_142:
; not an exception, we set the error code manually to 0
push 0
push 142
jmp interrupt_stubs_common

interrupt_stub_143:
; not an exception, we set the error code manually to 0
push 0
push 143
jmp interrupt_stubs_common

interrupt_stub_144:
; not an exception, we set the error code manually to 0
push 0
push 144
jmp interrupt_stubs_common

interrupt_stub_145:
; not an exception, we set the error code manually to 0
push 0
push 145
jmp interrupt_stubs_common

interrupt_stub_146:
; not an exception, we set the error code manually to 0
push 0
push 146
jmp interrupt_stubs_common

interrupt_stub_147:
; not an exception, we set the error code manually to 0
push 0
push 147
jmp interrupt_stubs_common

interrupt_stub_148:
; not an exception, we set the error code manually to 0
push 0
push 148
jmp interrupt_stubs_common

interrupt_stub_149:
; not an exception, we set the error code manually to 0
push 0
push 149
jmp interrupt_stubs_common

interrupt_stub_150:
; not an exception, we set the error code manually to 0
push 0
push 150
jmp interrupt_stubs_common

interrupt_stub_151:
; not an exception, we set the error code manually to 0
push 0
push 151
jmp interrupt_stubs_common

interrupt_stub_152:
; not an exception, we set the error code manually to 0
push 0
push 152
jmp interrupt_stubs_common

interrupt_stub_153:
; not an exception, we set the error code manually to 0
push 0
push 153
jmp interrupt_stubs_common

interrupt_stub_154:
; not an exception, we set the error code manually to 0
push 0
push 154
jmp interrupt_stubs_common

interrupt_stub_155:
; not an exception, we set the error code manually to 0
push 0
push 155
jmp interrupt_stubs_common

interrupt_stub_156:
; not an exception, we set the error code manually to 0
push 0
push 156
jmp interrupt_stubs_common

interrupt_stub_157:
; not an exception, we set the error code manually to 0
push 0
push 157
jmp interrupt_stubs_common

interrupt_stub_158:
; not an exception, we set the error code manually to 0
push 0
push 158
jmp interrupt_stubs_common

interrupt_stub_159:
; not an exception, we set the error code manually to 0
push 0
push 159
jmp interrupt_stubs_common

interrupt_stub_160:
; not an exception, we set the error code manually to 0
push 0
push 160
jmp interrupt_stubs_common

interrupt_stub_161:
; not an exception, we set the error code manually to 0
push 0
push 161
jmp interrupt_stubs_common

interrupt_stub_162:
; not an exception, we set the error code manually to 0
push 0
push 162
jmp interrupt_stubs_common

interrupt_stub_163:
; not an exception, we set the error code manually to 0
push 0
push 163
jmp interrupt_stubs_common

interrupt_stub_164:
; not an exception, we set the error code manually to 0
push 0
push 164
jmp interrupt_stubs_common

interrupt_stub_165:
; not an exception, we set the error code manually to 0
push 0
push 165
jmp interrupt_stubs_common

interrupt_stub_166:
; not an exception, we set the error code manually to 0
push 0
push 166
jmp interrupt_stubs_common

interrupt_stub_167:
; not an exception, we set the error code manually to 0
push 0
push 167
jmp interrupt_stubs_common

interrupt_stub_168:
; not an exception, we set the error code manually to 0
push 0
push 168
jmp interrupt_stubs_common

interrupt_stub_169:
; not an exception, we set the error code manually to 0
push 0
push 169
jmp interrupt_stubs_common

interrupt_stub_170:
; not an exception, we set the error code manually to 0
push 0
push 170
jmp interrupt_stubs_common

interrupt_stub_171:
; not an exception, we set the error code manually to 0
push 0
push 171
jmp interrupt_stubs_common

interrupt_stub_172:
; not an exception, we set the error code manually to 0
push 0
push 172
jmp interrupt_stubs_common

interrupt_stub_173:
; not an exception, we set the error code manually to 0
push 0
push 173
jmp interrupt_stubs_common

interrupt_stub_174:
; not an exception, we set the error code manually to 0
push 0
push 174
jmp interrupt_stubs_common

interrupt_stub_175:
; not an exception, we set the error code manually to 0
push 0
push 175
jmp interrupt_stubs_common

interrupt_stub_176:
; not an exception, we set the error code manually to 0
push 0
push 176
jmp interrupt_stubs_common

interrupt_stub_177:
; not an exception, we set the error code manually to 0
push 0
push 177
jmp interrupt_stubs_common

interrupt_stub_178:
; not an exception, we set the error code manually to 0
push 0
push 178
jmp interrupt_stubs_common

interrupt_stub_179:
; not an exception, we set the error code manually to 0
push 0
push 179
jmp interrupt_stubs_common

interrupt_stub_180:
; not an exception, we set the error code manually to 0
push 0
push 180
jmp interrupt_stubs_common

interrupt_stub_181:
; not an exception, we set the error code manually to 0
push 0
push 181
jmp interrupt_stubs_common

interrupt_stub_182:
; not an exception, we set the error code manually to 0
push 0
push 182
jmp interrupt_stubs_common

interrupt_stub_183:
; not an exception, we set the error code manually to 0
push 0
push 183
jmp interrupt_stubs_common

interrupt_stub_184:
; not an exception, we set the error code manually to 0
push 0
push 184
jmp interrupt_stubs_common

interrupt_stub_185:
; not an exception, we set the error code manually to 0
push 0
push 185
jmp interrupt_stubs_common

interrupt_stub_186:
; not an exception, we set the error code manually to 0
push 0
push 186
jmp interrupt_stubs_common

interrupt_stub_187:
; not an exception, we set the error code manually to 0
push 0
push 187
jmp interrupt_stubs_common

interrupt_stub_188:
; not an exception, we set the error code manually to 0
push 0
push 188
jmp interrupt_stubs_common

interrupt_stub_189:
; not an exception, we set the error code manually to 0
push 0
push 189
jmp interrupt_stubs_common

interrupt_stub_190:
; not an exception, we set the error code manually to 0
push 0
push 190
jmp interrupt_stubs_common

interrupt_stub_191:
; not an exception, we set the error code manually to 0
push 0
push 191
jmp interrupt_stubs_common

interrupt_stub_192:
; not an exception, we set the error code manually to 0
push 0
push 192
jmp interrupt_stubs_common

interrupt_stub_193:
; not an exception, we set the error code manually to 0
push 0
push 193
jmp interrupt_stubs_common

interrupt_stub_194:
; not an exception, we set the error code manually to 0
push 0
push 194
jmp interrupt_stubs_common

interrupt_stub_195:
; not an exception, we set the error code manually to 0
push 0
push 195
jmp interrupt_stubs_common

interrupt_stub_196:
; not an exception, we set the error code manually to 0
push 0
push 196
jmp interrupt_stubs_common

interrupt_stub_197:
; not an exception, we set the error code manually to 0
push 0
push 197
jmp interrupt_stubs_common

interrupt_stub_198:
; not an exception, we set the error code manually to 0
push 0
push 198
jmp interrupt_stubs_common

interrupt_stub_199:
; not an exception, we set the error code manually to 0
push 0
push 199
jmp interrupt_stubs_common

interrupt_stub_200:
; not an exception, we set the error code manually to 0
push 0
push 200
jmp interrupt_stubs_common

interrupt_stub_201:
; not an exception, we set the error code manually to 0
push 0
push 201
jmp interrupt_stubs_common

interrupt_stub_202:
; not an exception, we set the error code manually to 0
push 0
push 202
jmp interrupt_stubs_common

interrupt_stub_203:
; not an exception, we set the error code manually to 0
push 0
push 203
jmp interrupt_stubs_common

interrupt_stub_204:
; not an exception, we set the error code manually to 0
push 0
push 204
jmp interrupt_stubs_common

interrupt_stub_205:
; not an exception, we set the error code manually to 0
push 0
push 205
jmp interrupt_stubs_common

interrupt_stub_206:
; not an exception, we set the error code manually to 0
push 0
push 206
jmp interrupt_stubs_common

interrupt_stub_207:
; not an exception, we set the error code manually to 0
push 0
push 207
jmp interrupt_stubs_common

interrupt_stub_208:
; not an exception, we set the error code manually to 0
push 0
push 208
jmp interrupt_stubs_common

interrupt_stub_209:
; not an exception, we set the error code manually to 0
push 0
push 209
jmp interrupt_stubs_common

interrupt_stub_210:
; not an exception, we set the error code manually to 0
push 0
push 210
jmp interrupt_stubs_common

interrupt_stub_211:
; not an exception, we set the error code manually to 0
push 0
push 211
jmp interrupt_stubs_common

interrupt_stub_212:
; not an exception, we set the error code manually to 0
push 0
push 212
jmp interrupt_stubs_common

interrupt_stub_213:
; not an exception, we set the error code manually to 0
push 0
push 213
jmp interrupt_stubs_common

interrupt_stub_214:
; not an exception, we set the error code manually to 0
push 0
push 214
jmp interrupt_stubs_common

interrupt_stub_215:
; not an exception, we set the error code manually to 0
push 0
push 215
jmp interrupt_stubs_common

interrupt_stub_216:
; not an exception, we set the error code manually to 0
push 0
push 216
jmp interrupt_stubs_common

interrupt_stub_217:
; not an exception, we set the error code manually to 0
push 0
push 217
jmp interrupt_stubs_common

interrupt_stub_218:
; not an exception, we set the error code manually to 0
push 0
push 218
jmp interrupt_stubs_common

interrupt_stub_219:
; not an exception, we set the error code manually to 0
push 0
push 219
jmp interrupt_stubs_common

interrupt_stub_220:
; not an exception, we set the error code manually to 0
push 0
push 220
jmp interrupt_stubs_common

interrupt_stub_221:
; not an exception, we set the error code manually to 0
push 0
push 221
jmp interrupt_stubs_common

interrupt_stub_222:
; not an exception, we set the error code manually to 0
push 0
push 222
jmp interrupt_stubs_common

interrupt_stub_223:
; not an exception, we set the error code manually to 0
push 0
push 223
jmp interrupt_stubs_common

interrupt_stub_224:
; not an exception, we set the error code manually to 0
push 0
push 224
jmp interrupt_stubs_common

interrupt_stub_225:
; not an exception, we set the error code manually to 0
push 0
push 225
jmp interrupt_stubs_common

interrupt_stub_226:
; not an exception, we set the error code manually to 0
push 0
push 226
jmp interrupt_stubs_common

interrupt_stub_227:
; not an exception, we set the error code manually to 0
push 0
push 227
jmp interrupt_stubs_common

interrupt_stub_228:
; not an exception, we set the error code manually to 0
push 0
push 228
jmp interrupt_stubs_common

interrupt_stub_229:
; not an exception, we set the error code manually to 0
push 0
push 229
jmp interrupt_stubs_common

interrupt_stub_230:
; not an exception, we set the error code manually to 0
push 0
push 230
jmp interrupt_stubs_common

interrupt_stub_231:
; not an exception, we set the error code manually to 0
push 0
push 231
jmp interrupt_stubs_common

interrupt_stub_232:
; not an exception, we set the error code manually to 0
push 0
push 232
jmp interrupt_stubs_common

interrupt_stub_233:
; not an exception, we set the error code manually to 0
push 0
push 233
jmp interrupt_stubs_common

interrupt_stub_234:
; not an exception, we set the error code manually to 0
push 0
push 234
jmp interrupt_stubs_common

interrupt_stub_235:
; not an exception, we set the error code manually to 0
push 0
push 235
jmp interrupt_stubs_common

interrupt_stub_236:
; not an exception, we set the error code manually to 0
push 0
push 236
jmp interrupt_stubs_common

interrupt_stub_237:
; not an exception, we set the error code manually to 0
push 0
push 237
jmp interrupt_stubs_common

interrupt_stub_238:
; not an exception, we set the error code manually to 0
push 0
push 238
jmp interrupt_stubs_common

interrupt_stub_239:
; not an exception, we set the error code manually to 0
push 0
push 239
jmp interrupt_stubs_common

interrupt_stub_240:
; not an exception, we set the error code manually to 0
push 0
push 240
jmp interrupt_stubs_common

interrupt_stub_241:
; not an exception, we set the error code manually to 0
push 0
push 241
jmp interrupt_stubs_common

interrupt_stub_242:
; not an exception, we set the error code manually to 0
push 0
push 242
jmp interrupt_stubs_common

interrupt_stub_243:
; not an exception, we set the error code manually to 0
push 0
push 243
jmp interrupt_stubs_common

interrupt_stub_244:
; not an exception, we set the error code manually to 0
push 0
push 244
jmp interrupt_stubs_common

interrupt_stub_245:
; not an exception, we set the error code manually to 0
push 0
push 245
jmp interrupt_stubs_common

interrupt_stub_246:
; not an exception, we set the error code manually to 0
push 0
push 246
jmp interrupt_stubs_common

interrupt_stub_247:
; not an exception, we set the error code manually to 0
push 0
push 247
jmp interrupt_stubs_common

interrupt_stub_248:
; not an exception, we set the error code manually to 0
push 0
push 248
jmp interrupt_stubs_common

interrupt_stub_249:
; not an exception, we set the error code manually to 0
push 0
push 249
jmp interrupt_stubs_common

interrupt_stub_250:
; not an exception, we set the error code manually to 0
push 0
push 250
jmp interrupt_stubs_common

interrupt_stub_251:
; not an exception, we set the error code manually to 0
push 0
push 251
jmp interrupt_stubs_common

interrupt_stub_252:
; not an exception, we set the error code manually to 0
push 0
push 252
jmp interrupt_stubs_common

interrupt_stub_253:
; not an exception, we set the error code manually to 0
push 0
push 253
jmp interrupt_stubs_common

interrupt_stub_254:
; not an exception, we set the error code manually to 0
push 0
push 254
jmp interrupt_stubs_common

interrupt_stub_255:
; not an exception, we set the error code manually to 0
push 0
push 255
jmp interrupt_stubs_common

interrupt_stubs_common:
push ds
push es
push fs
push gs

pushad

mov ax,data_segment_selector
mov es, ax
mov ds, ax
push esp ; trap_frame* parameter
cld  ; C code following the sysV ABI requires DF to be clear on function entry
call handle_interrupt
add esp, 4

trap_return:
popad

pop gs
pop fs
pop es
pop ds

;skip trap_number and err
add esp, 8

iret
